name: i3d
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.6
  - pip
  - pip:
      - numpy==1.19.5
      - torch==1.10.2
      - opencv-python==4.6.0.66
      - av==8.0.3
      - PIMS==0.5
      - tqdm