name: i3d
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.6
  - pip
  - pip:
      - ffmpeg-python==0.2.0
      - natsort==8.1.0
      - numpy==1.19.5
      - Pillow==8.4.0
      - torch==1.10.2
      - opencv-python==4.6.0.66
      - pathos==0.2.8